# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);



### 测试信息提取
GET http://localhost:8352/user/test
Accept: application/json

### 查询所有
GET http://localhost:8352/user/
Accept: application/json

### 根据id查询
GET http://localhost:8352/user/5df6dc127c95b26a00910864
Accept: application/json

### 根据id删除
DELETE http://localhost:8352/user/5dfa32574a2003408ff3033b


### 新增用户
POST http://localhost:8352/user/
Content-Type: application/json

{
  "name": "webflux-8",
  "age": 18
}

###